---
title: "Data Manipulation"
author: "Ashley Kang"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import FAS csv files

Import my first csv

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv(file = "./data/FAS_pups.csv")
# pups_data = read_csv(file = "~/Desktop/data_wrangling/data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)

#first step = "print"" out data-set 
# in console, type dataset name and check"
```

```{r}
select(litters_data, group, litter_number, gd0_weight)


select(litters_data, litter_number, gd0_weight, pups_survive)
#tell select exactly what variables you're interested in
```

## specify range of variables

```{r}
select(litters_data, gd_of_birth:pups_survive)
## selecting evertyhing from gd of birth to pups survive

select(litters_data, group, gd_of_birth:pups_survive)
```

## can specify what you don't want to keep
```{r}
select(litters_data, -litter_number)
# keeping everything except litter number
```

## rename gd0_weight to gest_day_0_weight
```{r}
select(litters_data, group, litter_number, gest_day_0_weight = gd0_weight)
# select is designed to make it easy for you to select variables you care about
rename(litters_data, gest_day_0_weight = gd0_weight)
# rename is helpful if you have 1 or 2 variables you want to rename
```

## using select_helpers
```{r}
select(litters_data, starts_with("gd"))
# extracts only gd variables

select(litters_data, litter_number, starts_with("pup"))
# mix and match criteria

select(litters_data, litter_number, everything())

```

