---
title: "Data Import"
author: "Ashley Kang"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import FAS csv files

Import my first csv

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

# janitor is another package, you want to do janitor::clean_names as opposed to library(janitor)... clean because if tidyverse and janitor has the same command, R wil be confused
```

## Import FAS_pups csv files

Import pups data set also

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
# pups_data = read_csv(file = "~/Desktop/data_wrangling/data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)

#first step = "print"" out data-set 
# in console, type dataset name and check"
```

## Look at data

Looking at litters data

```{r}
head(litters_data)
tail(litters_data)
skimr::skim(litters_data)

# View(litters_data) in console will pop up the entire dataset
```

Skip some rows; omit variable names 

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

Parsing columns (column types)

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = "ccddiiii"
)
#being specific about column types
```

Looking at pups data

```{r}
pups_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
skimr::skim(pups_data)
```


